export const siteCopy = {
  brand: {
    name: "Prosefield",
    promise: "Make space for better writing.",
  },
  header: {
    signIn: "Sign in",
    signOut: "Sign out",
    cta: "Start your first page",
    menu: "Open menu",
    navBenefits: "Benefits",
    navPricing: "Pricing",
    navFaq: "FAQ",
  },
  auth: {
    registerTitle: "Create your account",
    registerLead: "Start with a quiet workspace of your own.",
    loginTitle: "Welcome back",
    loginLead: "Sign in to return to your documents.",
    emailLabel: "Email",
    passwordLabel: "Password",
    registerSubmit: "Create account",
    loginSubmit: "Sign in",
    haveAccount: "Already have an account?",
    needAccount: "Need an account?",
    genericError: "Email or password is incorrect.",
    networkError: "Something went wrong. Please try again.",
    passwordHint: "Use at least 8 characters.",
  },
  home: {
    eyebrow: "A focused home for your writing",
    headline: "Turn scattered thoughts into something worth reading.",
    supporting:
      "Prosefield gives your ideas a quiet, capable workspace—from the rough first line to the draft you are ready to share.",
    explore: "Explore the editor",
  },
  footer: {
    privacy: "Privacy",
    terms: "Terms",
  },
  subscribe: {
    title: "Subscribe to start writing",
    body: "One simple plan for a calm, private writing workspace.",
    checkoutCta: "Continue to secure checkout",
    checkoutBusy: "Starting checkout…",
    checkoutError: "Could not start checkout. Please try again.",
  },
  documents: {
    upgradeTitle: "Subscribe to start writing",
    upgradeBody:
      "Your own private document library with headings, lists, quotes, and emphasis.",
    upgradeCta: "Continue to secure checkout",
    listHeading: "Documents",
    newDocument: "New document",
    emptyTitle: "Your first page is waiting.",
    emptyBody: "Create a document to start writing.",
    deleteTitlePrefix: "Delete",
    deleteBody: "This can't be undone.",
    deleteCancel: "Cancel",
    deleteConfirm: "Delete document",
    deletedToast: "Document deleted.",
    save: "Save",
    saved: "Saved",
    unsaved: "Unsaved changes",
    saving: "Saving…",
    saveFailed: "Save failed. Try again.",
    titleLabel: "Document title",
    backToList: "All documents",
    editorLandmark: "Document editor",
  },
  billingStatus: {
    title: "Confirming payment",
    pending: "Confirming your payment with Stripe…",
    delayed:
      "We’re still waiting for Stripe to confirm your payment. Refresh this page or try again shortly.",
    failedTitle: "Payment didn't go through",
    failedBody: "No charge unlocked access. You can try checkout again.",
    tryAgain: "Try again",
  },
} as const;

export type SiteCopy = typeof siteCopy;
